; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Win11 Toggle Rounded Corners"
#define MyAppVersion "1.3"
#define MyAppPublisher "Rich Ayr"
#define MyAppURL "https://github.com/rich-ayr/win11-toggle-rounded-corners"
#define LogonTaskName "Run win11-toggle-rounded-corners as admin on logon"

[Setup]
; [sic] double brace is the escape for a literal '{'
AppId={{5B8824C9-B4BE-4B1C-AA9F-BA8362C44B96}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
AppCopyright=Copyright (C) 2026 Rich Ayr <rich-ayr@img.ws>, MIT License
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=LICENSE
PrivilegesRequired=admin
OutputBaseFilename=win11-toggle-rounded-corners-setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern
ArchitecturesAllowed=x64os
ArchitecturesInstallIn64BitMode=x64os
MissingRunOnceIdsWarning=no
OutputDir=build

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
; Place any regular files here
Source: "LICENSE"; DestDir: "{app}";
Source: "build\win11-toggle-rounded-corners.exe"; DestDir: "{app}"

[CustomMessages]
OptionsPageCaption=Rounded Corners Options
OptionsPageDescription=Choose how you want rounded corners to be handled
DisableOption=Disable rounded corners completely
SmallOption=Enable small rounded corners
LogonTaskDescription=Automatically run on logon
AllUsersScopeOption=For all administrators on this PC
CurrentUserScopeOption=For me only

[Code]
var
  OptionsPage: TWizardPage;
  DisableRadio: TRadioButton;
  SmallRadio: TRadioButton;
  LogonCheck: TCheckBox;
  // Own container; TRadioButton groups by parent, not by proximity.
  ScopePanel: TPanel;
  AllUsersRadio: TRadioButton;
  CurrentUserRadio: TRadioButton;

procedure LogonCheckClick(Sender: TObject);
begin
  ScopePanel.Enabled := LogonCheck.Checked;
end;

procedure InitializeWizard;
begin
  // Create custom options page
  OptionsPage := CreateCustomPage(wpSelectTasks, 
    ExpandConstant('{cm:OptionsPageCaption}'), 
    ExpandConstant('{cm:OptionsPageDescription}'));
  
  // Create radio buttons
  DisableRadio := TRadioButton.Create(OptionsPage);
  DisableRadio.Parent := OptionsPage.Surface;
  DisableRadio.Caption := ExpandConstant('{cm:DisableOption}');
  DisableRadio.Left := 0;
  DisableRadio.Top := 16;
  DisableRadio.Width := OptionsPage.SurfaceWidth;
  DisableRadio.Checked := True; // Default selection
  
  SmallRadio := TRadioButton.Create(OptionsPage);
  SmallRadio.Parent := OptionsPage.Surface;
  SmallRadio.Caption := ExpandConstant('{cm:SmallOption}');
  SmallRadio.Left := 0;
  SmallRadio.Top := 40;
  SmallRadio.Width := OptionsPage.SurfaceWidth;

  LogonCheck := TCheckBox.Create(OptionsPage);
  LogonCheck.Parent := OptionsPage.Surface;
  LogonCheck.Caption := ExpandConstant('{cm:LogonTaskDescription}');
  LogonCheck.Left := 0;
  LogonCheck.Top := 72;
  LogonCheck.Width := OptionsPage.SurfaceWidth;
  LogonCheck.Checked := True; // Default selection

  ScopePanel := TPanel.Create(OptionsPage);
  ScopePanel.Parent := OptionsPage.Surface;
  ScopePanel.Left := 20;
  ScopePanel.Top := 94;
  ScopePanel.Width := OptionsPage.SurfaceWidth - 20;
  ScopePanel.Height := 46;
  ScopePanel.BevelOuter := bvNone;
  ScopePanel.ParentBackground := True;
  ScopePanel.Caption := '';

  AllUsersRadio := TRadioButton.Create(OptionsPage);
  AllUsersRadio.Parent := ScopePanel;
  AllUsersRadio.Caption := ExpandConstant('{cm:AllUsersScopeOption}');
  AllUsersRadio.Left := 0;
  AllUsersRadio.Top := 0;
  AllUsersRadio.Width := ScopePanel.Width;
  AllUsersRadio.Checked := True; // Default selection

  CurrentUserRadio := TRadioButton.Create(OptionsPage);
  CurrentUserRadio.Parent := ScopePanel;
  CurrentUserRadio.Caption := ExpandConstant('{cm:CurrentUserScopeOption}');
  CurrentUserRadio.Left := 0;
  CurrentUserRadio.Top := 22;
  CurrentUserRadio.Width := ScopePanel.Width;

  LogonCheck.OnClick := @LogonCheckClick;
end;

function GetSelectedParameter(Param: String): String;
begin
  if DisableRadio.Checked then
    Result := '--disable'
  else if SmallRadio.Checked then
    Result := '--small'
  else
    Result := '--disable'; // fallback
end;

function RunSchTasks(const Params: String; var ResultCode: Integer): Boolean;
begin
  Result := Exec(ExpandConstant('{sys}\schtasks.exe'), Params, '', SW_HIDE,
    ewWaitUntilTerminated, ResultCode);
end;

// Started=False means schtasks never launched; ResultCode is a Win32 error then.
procedure ReportSchTasksFailure(const Started: Boolean; const ResultCode: Integer;
  const Summary, Consequence: String; const Silent: Boolean);
var
  Detail: String;
begin
  if Started and (ResultCode = 0) then
    Exit;

  if Started then
    Detail := 'schtasks.exe exited with code ' + IntToStr(ResultCode) + '.'
  else
    Detail := 'schtasks.exe could not be started: ' + SysErrorMessage(ResultCode);

  Log(Summary + ' ' + Detail);
  if not Silent then
    MsgBox(Summary + #13#10#13#10 + Detail + #13#10#13#10 + Consequence, mbError, MB_OK);
end;

function XmlEscape(const S: String): String;
begin
  Result := S;
  StringChangeEx(Result, '&', '&amp;', True); // must run first
  StringChangeEx(Result, '<', '&lt;', True);
  StringChangeEx(Result, '>', '&gt;', True);
  StringChangeEx(Result, '"', '&quot;', True);
end;

// Under elevation this is the elevating admin, which is the account we want:
// nobody else could satisfy HighestAvailable anyway.
function CurrentUserAccount: String;
begin
  Result := GetEnv('USERDOMAIN') + '\' + GetEnv('USERNAME');
end;

// Hand-built because the schtasks CLI cannot express a group principal or the
// battery settings below.
function LogonTaskXml: String;
var
  Account, Principal, Trigger: String;
begin
  if AllUsersRadio.Checked then
  begin
    // BUILTIN\Administrators. LogonType is schema-invalid next to GroupId.
    Principal := '<GroupId>S-1-5-32-544</GroupId>';
    Trigger := '<LogonTrigger><Enabled>true</Enabled></LogonTrigger>';
  end
  else
  begin
    Account := XmlEscape(CurrentUserAccount);
    Principal := '<UserId>' + Account + '</UserId>' +
      '<LogonType>InteractiveToken</LogonType>';
    // Scoped too; an open trigger would fire for users the principal cannot run as.
    Trigger := '<LogonTrigger><Enabled>true</Enabled>' +
      '<UserId>' + Account + '</UserId></LogonTrigger>';
  end;

  // Element order matters; the schema validates as a sequence. UTF-16 is not a
  // typo: schtasks decodes the file before parsing, so UTF-8 here is rejected.
  Result :=
    '<?xml version="1.0" encoding="UTF-16"?>' +
    '<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">' +
      '<RegistrationInfo>' +
        '<Description>' + XmlEscape('{#MyAppName}') + '</Description>' +
      '</RegistrationInfo>' +
      '<Triggers>' + Trigger + '</Triggers>' +
      '<Principals><Principal id="Author">' + Principal +
        '<RunLevel>HighestAvailable</RunLevel></Principal></Principals>' +
      '<Settings>' +
        '<MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>' +
        // schtasks defaults these to true, skipping the task on battery.
        '<DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>' +
        '<StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>' +
        '<StartWhenAvailable>true</StartWhenAvailable>' +
        '<Enabled>true</Enabled>' +
      '</Settings>' +
      '<Actions Context="Author"><Exec>' +
        '<Command>' +
          XmlEscape(ExpandConstant('{app}\win11-toggle-rounded-corners.exe')) +
        '</Command>' +
        '<Arguments>' + XmlEscape(GetSelectedParameter('')) + '</Arguments>' +
      '</Exec></Actions>' +
    '</Task>';
end;

procedure CreateLogonTask;
var
  XmlPath: String;
  Lines: TArrayOfString;
  ResultCode: Integer;
  Started: Boolean;
begin
  XmlPath := ExpandConstant('{tmp}\logon-task.xml');

  SetArrayLength(Lines, 1);
  Lines[0] := LogonTaskXml;
  // schtasks reads the encoding from the BOM this writes.
  if not SaveStringsToUTF8File(XmlPath, Lines, False) then
  begin
    Log('The logon task could not be created. Setup could not write ' + XmlPath + '.');
    if not WizardSilent then
      MsgBox('The logon task could not be created.' + #13#10#13#10 +
        'Setup could not write its task definition to ' + XmlPath + '.' + #13#10#13#10 +
        'The tool is installed and works; it just will not start automatically at logon.',
        mbError, MB_OK);
    Exit;
  end;

  Started := RunSchTasks('/Create /F /TN ' + #34 + '{#LogonTaskName}' + #34 +
    ' /XML ' + #34 + XmlPath + #34, ResultCode);
  ReportSchTasksFailure(Started, ResultCode, 'The logon task could not be created.',
    'The tool is installed and works; it just will not start automatically at logon.',
    WizardSilent);

  DeleteFile(XmlPath);
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if (CurStep = ssPostInstall) and LogonCheck.Checked then
    CreateLogonTask;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  ResultCode: Integer;
  Started: Boolean;
begin
  if CurUninstallStep <> usUninstall then
    Exit;

  // A missing task is not an error
  Started := RunSchTasks('/Query /TN ' + #34 + '{#LogonTaskName}' + #34, ResultCode);
  if not Started or (ResultCode <> 0) then
    Exit;

  Started := RunSchTasks('/Delete /F /TN ' + #34 + '{#LogonTaskName}' + #34, ResultCode);
  ReportSchTasksFailure(Started, ResultCode, 'The logon task could not be removed.',
    'Remove it manually in Task Scheduler, otherwise it will keep firing at logon and ' +
    'point at a program that no longer exists:' + #13#10 + '{#LogonTaskName}',
    UninstallSilent);
end;

[Run]
; The logon task is created in [Code] so its failures are reported
Filename: "{app}\win11-toggle-rounded-corners.exe"; \
  Description: "Run now"; \
  Parameters: "{code:GetSelectedParameter}"; \
  Flags: runhidden runascurrentuser nowait postinstall
