; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Win11 Toggle Rounded Corners"
#define MyAppVersion "1.3"
#define MyAppPublisher "Rich Ayr"
#define MyAppURL "https://github.com/rich-ayr/win11-toggle-rounded-corners"
#define LogonTaskName "Run win11-toggle-rounded-corners as admin on logon"

[Setup]
AppId={{5B8824C9-B4BE-4B1C-AA9F-BA8362C44B96}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
AppCopyright=Copyright (C) 2026 Rich Ayr <rich-ayr@img.ws>, MIT License
DefaultDirName={autopf}\{#MyAppName}
DefaultGroupName={#MyAppName}
DisableProgramGroupPage=yes
LicenseFile=LICENSE
PrivilegesRequired=admin
OutputBaseFilename=win11-toggle-rounded-corners-setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern
ArchitecturesAllowed=x64os
ArchitecturesInstallIn64BitMode=x64os
MissingRunOnceIdsWarning=no
OutputDir=build

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Files]
; Place any regular files here
Source: "LICENSE"; DestDir: "{app}";
Source: "build\win11-toggle-rounded-corners.exe"; DestDir: "{app}"

[CustomMessages]
OptionsPageCaption=Rounded Corners Options
OptionsPageDescription=Choose how you want rounded corners to be handled
DisableOption=Disable rounded corners completely
SmallOption=Enable small rounded corners
LogonTaskDescription=Automatically run on logon

[Code]
var
  OptionsPage: TWizardPage;
  DisableRadio: TRadioButton;
  SmallRadio: TRadioButton;
  LogonCheck: TCheckBox;

procedure InitializeWizard;
begin
  // Create custom options page
  OptionsPage := CreateCustomPage(wpSelectTasks, 
    ExpandConstant('{cm:OptionsPageCaption}'), 
    ExpandConstant('{cm:OptionsPageDescription}'));
  
  // Create radio buttons
  DisableRadio := TRadioButton.Create(OptionsPage);
  DisableRadio.Parent := OptionsPage.Surface;
  DisableRadio.Caption := ExpandConstant('{cm:DisableOption}');
  DisableRadio.Left := 0;
  DisableRadio.Top := 16;
  DisableRadio.Width := OptionsPage.SurfaceWidth;
  DisableRadio.Checked := True; // Default selection
  
  SmallRadio := TRadioButton.Create(OptionsPage);
  SmallRadio.Parent := OptionsPage.Surface;
  SmallRadio.Caption := ExpandConstant('{cm:SmallOption}');
  SmallRadio.Left := 0;
  SmallRadio.Top := 40;
  SmallRadio.Width := OptionsPage.SurfaceWidth;

  LogonCheck := TCheckBox.Create(OptionsPage);
  LogonCheck.Parent := OptionsPage.Surface;
  LogonCheck.Caption := ExpandConstant('{cm:LogonTaskDescription}');
  LogonCheck.Left := 0;
  LogonCheck.Top := 72;
  LogonCheck.Width := OptionsPage.SurfaceWidth;
  LogonCheck.Checked := True; // Default selection
end;

function GetSelectedParameter(Param: String): String;
begin
  if DisableRadio.Checked then
    Result := '--disable'
  else if SmallRadio.Checked then
    Result := '--small'
  else
    Result := '--disable'; // fallback
end;

function RunSchTasks(const Params: String; var ResultCode: Integer): Boolean;
begin
  Result := Exec(ExpandConstant('{sys}\schtasks.exe'), Params, '', SW_HIDE,
    ewWaitUntilTerminated, ResultCode);
end;

// Started=False means schtasks never launched; ResultCode is a Win32 error then.
procedure ReportSchTasksFailure(const Started: Boolean; const ResultCode: Integer;
  const Summary, Consequence: String; const Silent: Boolean);
var
  Detail: String;
begin
  if Started and (ResultCode = 0) then
    Exit;

  if Started then
    Detail := 'schtasks.exe exited with code ' + IntToStr(ResultCode) + '.'
  else
    Detail := 'schtasks.exe could not be started: ' + SysErrorMessage(ResultCode);

  Log(Summary + ' ' + Detail);
  if not Silent then
    MsgBox(Summary + #13#10#13#10 + Detail + #13#10#13#10 + Consequence, mbError, MB_OK);
end;

procedure CreateLogonTask;
var
  Params: String;
  ResultCode: Integer;
  Started: Boolean;
begin
  // /TR is one command line; single-quote the path so the args stay separable.
  Params := '/Create /F /RL highest /SC onlogon' +
    ' /TN ' + #34 + '{#LogonTaskName}' + #34 +
    ' /TR ' + #34 + #39 + ExpandConstant('{app}\win11-toggle-rounded-corners.exe') + #39 +
    ' ' + GetSelectedParameter('') + #34;

  Started := RunSchTasks(Params, ResultCode);
  ReportSchTasksFailure(Started, ResultCode, 'The logon task could not be created.',
    'The tool is installed and works; it just will not start automatically at logon.',
    WizardSilent);
end;

procedure CurStepChanged(CurStep: TSetupStep);
begin
  if (CurStep = ssPostInstall) and LogonCheck.Checked then
    CreateLogonTask;
end;

procedure CurUninstallStepChanged(CurUninstallStep: TUninstallStep);
var
  ResultCode: Integer;
  Started: Boolean;
begin
  if CurUninstallStep <> usUninstall then
    Exit;

  // A missing task is not an error
  Started := RunSchTasks('/Query /TN ' + #34 + '{#LogonTaskName}' + #34, ResultCode);
  if not Started or (ResultCode <> 0) then
    Exit;

  Started := RunSchTasks('/Delete /F /TN ' + #34 + '{#LogonTaskName}' + #34, ResultCode);
  ReportSchTasksFailure(Started, ResultCode, 'The logon task could not be removed.',
    'Remove it manually in Task Scheduler, otherwise it will keep firing at logon and ' +
    'point at a program that no longer exists:' + #13#10 + '{#LogonTaskName}',
    UninstallSilent);
end;

[Run]
; The logon task is created in [Code] so its failures are reported
Filename: "{app}\win11-toggle-rounded-corners.exe"; \
  Description: "Run now"; \
  Parameters: "{code:GetSelectedParameter}"; \
  Flags: runhidden runascurrentuser nowait postinstall
